// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtQS80KJelVEadYlmeh9MroxL1kfinso4',
    appId: '1:421005691714:web:7c7375de363041ab5b96db',
    messagingSenderId: '421005691714',
    projectId: 'signlanguage-d549e',
    authDomain: 'signlanguage-d549e.firebaseapp.com',
    storageBucket: 'signlanguage-d549e.appspot.com',
    measurementId: 'G-08P9Z8E7Z3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf8RFRq_YkPNYZooIj0Ioo9BE_0gyVNSs',
    appId: '1:421005691714:android:f24267f83ad04b555b96db',
    messagingSenderId: '421005691714',
    projectId: 'signlanguage-d549e',
    storageBucket: 'signlanguage-d549e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6uVn21DbKboQ_cNMPCeu5nJrGjkdWF5M',
    appId: '1:421005691714:ios:bcdcc082cf94d9595b96db',
    messagingSenderId: '421005691714',
    projectId: 'signlanguage-d549e',
    storageBucket: 'signlanguage-d549e.appspot.com',
    iosBundleId: 'com.example.signLangFlut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6uVn21DbKboQ_cNMPCeu5nJrGjkdWF5M',
    appId: '1:421005691714:ios:bcdcc082cf94d9595b96db',
    messagingSenderId: '421005691714',
    projectId: 'signlanguage-d549e',
    storageBucket: 'signlanguage-d549e.appspot.com',
    iosBundleId: 'com.example.signLangFlut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtQS80KJelVEadYlmeh9MroxL1kfinso4',
    appId: '1:421005691714:web:d6edaffc649e888c5b96db',
    messagingSenderId: '421005691714',
    projectId: 'signlanguage-d549e',
    authDomain: 'signlanguage-d549e.firebaseapp.com',
    storageBucket: 'signlanguage-d549e.appspot.com',
    measurementId: 'G-29HE7902KN',
  );
}
